### ISSUE TITLE
Fatal error: tclap/CmdLine.h: No such file or directory

### ISSUE THREAD

**Issue by acesnik** [mateidavid/nanocall#1]
I'm trying to install and try out nanocall, and it looks like one of the dependencies for nanocall.cpp might be missing. 

Here's what I've done so far:
git clone https://github.com/mateidavid/nanocall.git
cd nanocall
mkdir build
cd build
cmake ../src -DCMAKE_INSTALL_PREFIX=~/Documents/nanocall -DBUILD_HDF5=1

The installation completed for hdf5, but then I encountered this error in this step:
[81%] Built target version
Scanning dependencies of target nanocall
[90%] Building CXX object nanocall/CMakeFiles/nanocall.dir/nanocall.cpp.o
/home/user/Documents/nanocall/src/nanocall/nanocall.cpp:4:27: fatal error: tclap/CmdLine.h: No such file or directory

compilation terminated.
make[2]: *** [nanocall/CMakeFiles/nanocall.dir/nanocall.cpp.o] Error 1
make[1]: *** [nanocall/CMakeFiles/nanocall.dir/all] Error 2

I'm not sure what this missing dependency is. Is there a chance you could help out with this?

Thanks,

Anthony

**Comment by jts** [comment]
Hi Anthony,

When cloning nanocall you need the `--recursive` flag to pull in the dependencies. Can you add this flag and try again?

Jared

**Comment by acesnik** [comment]
Perfect -- it completed the build! Thanks for pointing that out so quickly.

**Comment by xubin2015** [comment]
hello
i am a little bird and want to use the TCLAP/CMDLINE，
can you help me to install the tclap?
thanks

**Comment by jts** [comment]
Hi,

You need to use the `--recursive` flag when cloning the repository.

Jared
