### ISSUE TITLE
error: default argument for template parameter for class enclosing

### ISSUE THREAD

**Issue by tanij** [mateidavid/nanocall#4]
Hi, 

I'm getting an error while trying to install nanocall. This is what I do:

mkdir /NanocallSource && cd /NanocallSource
git clone --recursive https://github.com/mateidavid/nanocall.git
cd nanocall
mkdir build && cd build
cmake ../src -DCMAKE_INSTALL_PREFIX=~/NanocallInstall -DBUILD_HDF5=1
make

when at [90%] Building CXX object nanocall/CMakeFiles/nanocall.dir/nanocall.cpp.o 
I first get a bunch of warnings from lines 204-456:

`In file included from /home/duckietani/NanocallSource/nanocall/src/fast5/src/fast5.hpp:16:0,
                 from /home/duckietani/NanocallSource/nanocall/src/nanocall/Event.hpp:9,
                 from /home/duckietani/NanocallSource/nanocall/src/nanocall/Pore_Model.hpp:20,
                 from /home/duckietani/NanocallSource/nanocall/src/nanocall/nanocall.cpp:10:
/home/duckietani/NanocallSource/nanocall/src/fast5/src/hdf5_tools.hpp: In static member function ‘static const std::pair<const char*, std::function<bool(void*)> >& hdf5_tools::detail::Util::get_fcn_info(void*)’:
/home/duckietani/NanocallSource/nanocall/src/fast5/src/hdf5_tools.hpp:204:27: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Wpedantic]
                 { (void*)&H5Aclose,
                           ^`

and finally an error:

`In file included from /home/duckietani/NanocallSource/nanocall/src/nanocall/nanocall.cpp:10:0:
/home/duckietani/NanocallSource/nanocall/src/nanocall/Pore_Model.hpp: In function ‘std::istream& operator>>(std::istream&, Pore_Model<Float_Type, Kmer_Size>&)’:
/home/duckietani/NanocallSource/nanocall/src/nanocall/Pore_Model.hpp:278:83: error: default argument for template parameter for class enclosing ‘operator>>(std::istream&, Pore_Model<Float_Type, Kmer_Size>&)::__lambda57’
             [] (const Pore_Model_State_Type& lhs, const Pore_Model_State_Type& rhs)
                                                                                   ^
compilation terminated due to -fmax-errors=1.
make[2]: *** [nanocall/CMakeFiles/nanocall.dir/nanocall.cpp.o] Error 1
make[1]: *** [nanocall/CMakeFiles/nanocall.dir/all] Error 2
make: *** [all] Error 2`

Ideas on how to fix would be helpful. Thanks!

**Comment by mateidavid** [comment]
Hopefully fixed now. The error was probably this gcc 4.8 bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57775 , http://stackoverflow.com/questions/23181238/error-with-lambda-in-operator-of-template-class-with-default-argument . Let me know if it works.

**Comment by tanij** [comment]
The error no longer shows up. Thanks!
