### ISSUE TITLE
Weird mean value in r9 models

### ISSUE THREAD

**Issue by usamec** [mateidavid/nanocall#6]
Hi,
I compared r9 template model with my own and mostly we have similar values (up to scaling), but your mean value for CCTAGG looks to be -4.612661, which looks way of (most values are between 50 and 120). I extracted it from line 27549 from here https://github.com/mateidavid/nanocall/blob/master/src/builtin_models/builtin_model_init_lists.inl

**Comment by jts** [comment]
This was an error in the model provided by ONT. We'll fix it. 

Out of curiosity, is your training code available?

**Comment by mateidavid** [comment]
Fixed in 3cec0edc17d3cade10097f098bd1062acc97f0c2, now merged into `master`.
