### ISSUE TITLE
Segmentation Fault (Core Dump) with one read

### ISSUE THREAD

**Issue by genotypic** [mateidavid/nanocall#7]
Hi,

I ran the Nanocall with bunch of reads, which I faced the "Segmentation Fault (Core Dump)" error. As to check further I checked with only one read from the dataset, but still the error persist.
command I used.

`nanocall T1700_PC_20160614_FNFAD17088_MN17202_14630_ch97_read93_strand.fast5 > output_test.fa`

The error I got was.

`= main.2 nanocall.cpp:906 main program: nanocall
= main.2 nanocall.cpp:907 main version: v0.6.5
= main.2 nanocall.cpp:908 main args: T1700_PC_20160614_FNFAD17088_MN17202_14630_ch97_read93_strand.fast5
= main.2 nanocall.cpp:909 main num_threads=1
= main.2 nanocall.cpp:977 main train=1
= main.2 nanocall.cpp:980 main only_train=0
= main.2 nanocall.cpp:981 main train_scaling=1
= main.2 nanocall.cpp:982 main train_transitions=1
= main.2 nanocall.cpp:985 main double_strands_scaling=1
= main.2 nanocall.cpp:986 main scaling_num_events=200
= main.2 nanocall.cpp:987 main scaling_max_rounds=10
= main.2 nanocall.cpp:988 main scaling_min_progress=1
= main.2 nanocall.cpp:989 main scaling_select_threshold=20
= main.2 nanocall.cpp:158 init_models loaded builtin module [r9.t.006.ont.model] for strand [0] statistics [mean=87.1883, stdv=12.9876]
= main.2 nanocall.cpp:158 init_models loaded builtin module [r9.c.p1.006.ont.model] for strand [1] statistics [mean=87.1883, stdv=12.9876]
= main.2 nanocall.cpp:158 init_models loaded builtin module [r9.c.p2.006.ont.model] for strand [1] statistics [mean=92.5249, stdv=13.1801]
= main.2 nanocall.cpp:183 init_transitions init_state_transitions pr_skip=[0.3], pr_stay=[0.1]
= main.2 nanocall.cpp:221 init_files adding input file [T1700_PC_20160614_FNFAD17088_MN17202_14630_ch97_read93_strand.fast5]
Segmentation fault (core dumped)
`
Please give a solution for this problem.
Thank you.

**Comment by mateidavid** [comment]
Can you send me that single file? Or put it in a place where I can download it from?

**Comment by genotypic** [comment]
I have attached the single .fast5 file. 
Thank you.
[test.fast5.zip](https://github.com/mateidavid/nanocall/files/398694/test.fast5.zip)

**Comment by mateidavid** [comment]
Fixed in 87884aa4d5bc7af4fd74c20eb89e2d67a9e25119. Thanks for the report.

**Comment by genotypic** [comment]
Dear David,

I updated to the latest commit. Ran the Nanocall with the above commands. Nanocall is running perfect without any errors, but I am getting empty .fa file at the end. 

What could be the reason?? I thought it may be due to the read doesnt have event called. I ran it through a bunch of reads but got same empty .fa file. Tried with  --min-ed-events parameter with 100 also still the output is empty file.

Regards,
Genotypic

**Comment by mateidavid** [comment]
The read you sent has no EventDetection done on it at all:

    HDF5 "test.fast5" {
    FILE_CONTENTS {
     group      /
     group      /Raw
     group      /Raw/Reads
     group      /Raw/Reads/Read_3742
     dataset    /Raw/Reads/Read_3742/Signal
     group      /UniqueGlobalKey
     group      /UniqueGlobalKey/channel_id
     group      /UniqueGlobalKey/context_tags
     group      /UniqueGlobalKey/tracking_id
     }
    }

Nanocall needs EventDetection to do anything. Usually this is done by MinKNOW under `/Analyses/EventDetection_000`, but for a while (~Apr-Jun), this was completely unusable (very very bad) on R9 data, so I added the option to use `/Analyses/EventDetection_001` which is done by Metrichor. I'm not sure what the latest MinKNOW is doing, it's changing too fast.

**Comment by genotypic** [comment]
Dear Team ONT

We have successfully downloaded nanonet 2D basecaller. But we are unable to install nanonet 2D basecaller in our machine. we are getting following import error.

ImportError: cannot import name viterbi_2d

Looking forward from you.

**Comment by jts** [comment]
I think you reported this problem on the wrong github repository, this is nanocall not nanonet.

Jared
