### ISSUE TITLE
Build on Mac: clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by TasnimGharaibeh** [mateidavid/nanocall#8]
Hello,
I am trying to build the project on a mac machine, the build reaches 43% then this error popped out: 

```
clang: warning: argument unused during compilation: '-pthread'
ld: unknown option: --as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nanocall/list-directory] Error 1
make[1]: *** [nanocall/CMakeFiles/list-directory.dir/all] Error 2
make: *** [all] Error 2

```
Any ideas how to solve this issue?

**Comment by mateidavid** [comment]
I don't have access to OSX. I tried to reproduce this under Docker with `debian:testing` and Clang 3.5, but it works just fine.

The first thing you could try is to enable a detailed log of the build process:
```
cmake ~/code/nanocall/src -DCMAKE_VERBOSE_MAKEFILE=True
make |& tee make.log
```
Then, in `make.log` you will see exactly the command line that fails.

Another thing to try is to remove `--as-needed`. (Perhaps the Clang version on OSX is older and doesn't support it? However, this is unclear unless we see the exact command line that fails.) To remove it, open `src/CMakeLists.txt` and comment out line 168 where it gets set. This might or might not work, but it's definitely something to try.

**Comment by TasnimGharaibeh** [comment]
Thank you for your prompt reply, I removed --as-needed flag and now getting this error: 

Users/xxx/nanocall/src/nanocall/global_assert.hpp:22:16: error: 
      thread-local storage is not supported for the current target
        static thread_local std::string _global_msg;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
make[2]: *** [nanocall/CMakeFiles/nanocall.dir/nanocall.cpp.o] Error 1
make[1]: *** [nanocall/CMakeFiles/nanocall.dir/all] Error 2
make: *** [all] Error 2

Looks like Apple's clang does not support thread_local?
I am using 
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0

Any suggestions are welcome!
Thanks

**Comment by mateidavid** [comment]
That's a showstopper, Nanocall relies on such C++11 concepts. The whole point was to avoid other dependencies such as OpenMP.

This is unbelievable from Apple: http://stackoverflow.com/a/29929949/717706

Anyhow, it looks like the options are:
- Xcode 8 Beta, as per that post.
- Docker
- Use another compiler, perhaps GCC via Homebrew:
http://apple.stackexchange.com/questions/38222/how-do-i-install-gcc-via-homebrew

**Comment by TasnimGharaibeh** [comment]
Thanks again for the quick reply. I installed Xcode 8 Beta and it worked fine. Also, Docker is working fine. 

Thanks
